"""add slug and site_metadata to clinic_hdr

Revision ID: 1cb00e1c6463
Revises: 3d3db622c32b
Create Date: 2026-06-24 10:32:07.189072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb00e1c6463'
down_revision: Union[str, Sequence[str], None] = '3d3db622c32b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_mda_clinic_hdr', sa.Column('slug', sa.String(length=10), nullable=True))
    op.add_column('app_mda_clinic_hdr', sa.Column('site_metadata', sa.JSON(), nullable=True))
    op.create_index('idx_app_mda_clinic_hdr_slug', 'app_mda_clinic_hdr', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_app_mda_clinic_hdr_slug', table_name='app_mda_clinic_hdr')
    op.drop_column('app_mda_clinic_hdr', 'site_metadata')
    op.drop_column('app_mda_clinic_hdr', 'slug')
    # ### end Alembic commands ###
