"""add created_by_guid and address to app_mda_clinic_hdr

Revision ID: 2d8a3f1e5c4d
Revises: 35c46794f9a3
Create Date: 2026-06-25 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2d8a3f1e5c4d'
down_revision: Union[str, Sequence[str], None] = '35c46794f9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_mda_clinic_hdr', 
                  sa.Column('created_by_guid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('app_mda_clinic_hdr', 
                  sa.Column('address', sa.Text(), nullable=True))
    op.create_index('idx_app_mda_clinic_hdr_created_by', 
                    'app_mda_clinic_hdr', ['created_by_guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_app_mda_clinic_hdr_created_by', table_name='app_mda_clinic_hdr')
    op.drop_column('app_mda_clinic_hdr', 'address')
    op.drop_column('app_mda_clinic_hdr', 'created_by_guid')
    # ### end Alembic commands ###