"""add additional_remarks to appointment_note

Revision ID: 3a5be4639cd1
Revises: 9b4741dfefb3
Create Date: 2026-06-18 07:48:38.880188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5be4639cd1'
down_revision: Union[str, Sequence[str], None] = '9b4741dfefb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_mda_appointment_note', sa.Column('additional_remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_mda_appointment_note', 'additional_remarks')
    # ### end Alembic commands ###
