"""tables for chat hdr and chat transcripts

Revision ID: 3d3db622c32b
Revises: b1f3c7a9d2e4
Create Date: 2026-06-22 06:39:21.508502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3db622c32b'
down_revision: Union[str, Sequence[str], None] = 'b1f3c7a9d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_mda_lead_chat_hdr',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('lead_guid', sa.UUID(), nullable=True),
    sa.Column('triage_summary', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_chat_hdr_created_date', 'app_mda_lead_chat_hdr', ['created_date'], unique=False)
    op.create_index('idx_chat_hdr_lead_guid', 'app_mda_lead_chat_hdr', ['lead_guid'], unique=False)
    op.create_table('app_mda_lead_chat_transcript',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('chat_hdr_guid', sa.UUID(), nullable=True),
    sa.Column('msg_content', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_transcript_created_date', 'app_mda_lead_chat_transcript', ['created_date'], unique=False)
    op.create_index('idx_transcript_hdr_guid', 'app_mda_lead_chat_transcript', ['chat_hdr_guid'], unique=False)
    op.create_index('idx_transcript_sender', 'app_mda_lead_chat_transcript', ['sender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transcript_sender', table_name='app_mda_lead_chat_transcript')
    op.drop_index('idx_transcript_hdr_guid', table_name='app_mda_lead_chat_transcript')
    op.drop_index('idx_transcript_created_date', table_name='app_mda_lead_chat_transcript')
    op.drop_table('app_mda_lead_chat_transcript')
    op.drop_index('idx_chat_hdr_lead_guid', table_name='app_mda_lead_chat_hdr')
    op.drop_index('idx_chat_hdr_created_date', table_name='app_mda_lead_chat_hdr')
    op.drop_table('app_mda_lead_chat_hdr')
    # ### end Alembic commands ###
