"""add running_no to appointment

Revision ID: 3e8287385537
Revises: 3a5be4639cd1
Create Date: 2026-06-19 22:33:33.951753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8287385537'
down_revision: Union[str, Sequence[str], None] = '3a5be4639cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_mda_appointment', sa.Column('running_no', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_mda_appointment', 'running_no')
    # ### end Alembic commands ###
