"""table changeset for clinical report

Revision ID: 4ac21f2cd76c
Revises: 74dc6f2a15de
Create Date: 2026-06-21 07:47:40.534838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ac21f2cd76c'
down_revision: Union[str, Sequence[str], None] = '74dc6f2a15de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_mda_clinical_report',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('appointment_session_guid', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_observations', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('red_flags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('lifestyle_and_diet', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('care_plan_steps', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('form_discrepancies', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('patient_comprehension_rating', sa.String(length=50), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_clinical_report_appt_session', 'app_mda_clinical_report', ['appointment_session_guid'], unique=False)
    op.create_index('idx_clinical_report_created_date', 'app_mda_clinical_report', ['created_date'], unique=False)
    op.create_index('idx_clinical_report_updated_date', 'app_mda_clinical_report', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_clinical_report_updated_date', table_name='app_mda_clinical_report')
    op.drop_index('idx_clinical_report_created_date', table_name='app_mda_clinical_report')
    op.drop_index('idx_clinical_report_appt_session', table_name='app_mda_clinical_report')
    op.drop_table('app_mda_clinical_report')
    # ### end Alembic commands ###
