"""add transcript columns to appointment_session

Revision ID: 6ae79be1298d
Revises: a3fba4e55ea3
Create Date: 2026-06-17 07:55:02.911615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae79be1298d'
down_revision: Union[str, Sequence[str], None] = 'a3fba4e55ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_mda_appointment_session', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('app_mda_appointment_session', sa.Column('transcription_status', sa.String(length=50), nullable=True))
    op.add_column('app_mda_appointment_session', sa.Column('transcript_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_mda_appointment_session', 'transcript_metadata')
    op.drop_column('app_mda_appointment_session', 'transcription_status')
    op.drop_column('app_mda_appointment_session', 'transcript')
    # ### end Alembic commands ###
