"""add appointment_guid and patient_guid to appointment_note

Revision ID: 9b4741dfefb3
Revises: d8e28cfe4fa2
Create Date: 2026-06-18 07:41:06.369430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4741dfefb3'
down_revision: Union[str, Sequence[str], None] = 'd8e28cfe4fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_mda_appointment_note', sa.Column('appointment_guid', sa.UUID(), nullable=True))
    op.add_column('app_mda_appointment_note', sa.Column('patient_guid', sa.UUID(), nullable=True))
    op.create_index('idx_app_mda_appointment_note_apmt', 'app_mda_appointment_note', ['appointment_guid'], unique=False)
    op.create_index('idx_app_mda_appointment_note_patient_guid', 'app_mda_appointment_note', ['patient_guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_app_mda_appointment_note_patient_guid', table_name='app_mda_appointment_note')
    op.drop_index('idx_app_mda_appointment_note_apmt', table_name='app_mda_appointment_note')
    op.drop_column('app_mda_appointment_note', 'patient_guid')
    op.drop_column('app_mda_appointment_note', 'appointment_guid')
    # ### end Alembic commands ###
