"""add all 13 tables

Revision ID: a3fba4e55ea3
Revises: 
Create Date: 2026-06-16 18:04:55.187139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fba4e55ea3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_mda_appointment',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('clinic_guid', sa.UUID(), nullable=True),
    sa.Column('doctor_guid', sa.UUID(), nullable=True),
    sa.Column('patient_guid', sa.UUID(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('appointment_status', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_appointment_clinic_guid', 'app_mda_appointment', ['clinic_guid'], unique=False)
    op.create_index('idx_app_mda_appointment_created_date', 'app_mda_appointment', ['created_date'], unique=False)
    op.create_index('idx_app_mda_appointment_doctor_guid', 'app_mda_appointment', ['doctor_guid'], unique=False)
    op.create_index('idx_app_mda_appointment_patient_guid', 'app_mda_appointment', ['patient_guid'], unique=False)
    op.create_index('idx_app_mda_appointment_scheduled_end', 'app_mda_appointment', ['scheduled_end'], unique=False)
    op.create_index('idx_app_mda_appointment_scheduled_start', 'app_mda_appointment', ['scheduled_start'], unique=False)
    op.create_index('idx_app_mda_appointment_status', 'app_mda_appointment', ['status'], unique=False)
    op.create_index('idx_app_mda_appointment_status_of_appt', 'app_mda_appointment', ['appointment_status'], unique=False)
    op.create_index('idx_app_mda_appointment_updated_date', 'app_mda_appointment', ['updated_date'], unique=False)
    op.create_table('app_mda_appointment_session',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('appointment_guid', sa.UUID(), nullable=True),
    sa.Column('doctor_guid', sa.UUID(), nullable=True),
    sa.Column('audio_stream_url', sa.Text(), nullable=True),
    sa.Column('is_reviewed_by_doctor', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_appointment_session_appointment_guid', 'app_mda_appointment_session', ['appointment_guid'], unique=False)
    op.create_index('idx_app_mda_appointment_session_created_date', 'app_mda_appointment_session', ['created_date'], unique=False)
    op.create_index('idx_app_mda_appointment_session_doctor_guid', 'app_mda_appointment_session', ['doctor_guid'], unique=False)
    op.create_index('idx_app_mda_appointment_session_reviewed_by_doctor', 'app_mda_appointment_session', ['is_reviewed_by_doctor'], unique=False)
    op.create_index('idx_app_mda_appointment_session_status', 'app_mda_appointment_session', ['status'], unique=False)
    op.create_index('idx_app_mda_appointment_session_updated_date', 'app_mda_appointment_session', ['updated_date'], unique=False)
    op.create_table('app_mda_clinic_hdr',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_clinic_hdr_created_date', 'app_mda_clinic_hdr', ['created_date'], unique=False)
    op.create_index('idx_app_mda_clinic_hdr_name', 'app_mda_clinic_hdr', ['name'], unique=False)
    op.create_index('idx_app_mda_clinic_hdr_status', 'app_mda_clinic_hdr', ['status'], unique=False)
    op.create_index('idx_app_mda_clinic_hdr_updated_date', 'app_mda_clinic_hdr', ['updated_date'], unique=False)
    op.create_table('app_mda_doctor',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('user_guid', sa.UUID(), nullable=True),
    sa.Column('clinic_hdr_guid', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_doctor_clinic_hdr_guid', 'app_mda_doctor', ['clinic_hdr_guid'], unique=False)
    op.create_index('idx_app_mda_doctor_created_date', 'app_mda_doctor', ['created_date'], unique=False)
    op.create_index('idx_app_mda_doctor_email', 'app_mda_doctor', ['email'], unique=False)
    op.create_index('idx_app_mda_doctor_name', 'app_mda_doctor', ['name'], unique=False)
    op.create_index('idx_app_mda_doctor_phone', 'app_mda_doctor', ['phone'], unique=False)
    op.create_index('idx_app_mda_doctor_specialty', 'app_mda_doctor', ['specialty'], unique=False)
    op.create_index('idx_app_mda_doctor_status', 'app_mda_doctor', ['status'], unique=False)
    op.create_index('idx_app_mda_doctor_user_guid', 'app_mda_doctor', ['user_guid'], unique=False)
    op.create_table('app_mda_doctor_availability',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('doctor_guid', sa.UUID(), nullable=True),
    sa.Column('day_of_week', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_doctor_availability_created_date', 'app_mda_doctor_availability', ['created_date'], unique=False)
    op.create_index('idx_app_mda_doctor_availability_day_of_week', 'app_mda_doctor_availability', ['day_of_week'], unique=False)
    op.create_index('idx_app_mda_doctor_availability_doctor_guid', 'app_mda_doctor_availability', ['doctor_guid'], unique=False)
    op.create_index('idx_app_mda_doctor_availability_end_time', 'app_mda_doctor_availability', ['end_time'], unique=False)
    op.create_index('idx_app_mda_doctor_availability_slot_duration_minutes', 'app_mda_doctor_availability', ['slot_duration_minutes'], unique=False)
    op.create_index('idx_app_mda_doctor_availability_start_time', 'app_mda_doctor_availability', ['start_time'], unique=False)
    op.create_index('idx_app_mda_doctor_availability_status', 'app_mda_doctor_availability', ['status'], unique=False)
    op.create_index('idx_app_mda_doctor_availability_updated_date', 'app_mda_doctor_availability', ['updated_date'], unique=False)
    op.create_table('app_mda_doctor_cred',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('doctor_guid', sa.UUID(), nullable=True),
    sa.Column('file_matadata', sa.JSON(), nullable=True),
    sa.Column('remarks_1', sa.Text(), nullable=True),
    sa.Column('remarks_2', sa.Text(), nullable=True),
    sa.Column('remarks_3', sa.Text(), nullable=True),
    sa.Column('remarks_4', sa.Text(), nullable=True),
    sa.Column('remarks_5', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_doctor_cred_created_date', 'app_mda_doctor_cred', ['created_date'], unique=False)
    op.create_index('idx_app_mda_doctor_cred_doctor_guid', 'app_mda_doctor_cred', ['doctor_guid'], unique=False)
    op.create_index('idx_app_mda_doctor_cred_status', 'app_mda_doctor_cred', ['status'], unique=False)
    op.create_table('app_mda_doctor_patient_link',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('doctor_guid', sa.UUID(), nullable=True),
    sa.Column('patient_guid', sa.UUID(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_doctor_patient_link_created_date', 'app_mda_doctor_patient_link', ['created_date'], unique=False)
    op.create_index('idx_app_mda_doctor_patient_link_doctor_guid', 'app_mda_doctor_patient_link', ['doctor_guid'], unique=False)
    op.create_index('idx_app_mda_doctor_patient_link_patient_guid', 'app_mda_doctor_patient_link', ['patient_guid'], unique=False)
    op.create_index('idx_app_mda_doctor_patient_link_status', 'app_mda_doctor_patient_link', ['status'], unique=False)
    op.create_index('idx_app_mda_doctor_patient_link_updated_date', 'app_mda_doctor_patient_link', ['updated_date'], unique=False)
    op.create_table('app_mda_follow_up_queue',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('appointment_guid', sa.UUID(), nullable=True),
    sa.Column('patient_guid', sa.UUID(), nullable=True),
    sa.Column('scheduled_cron', sa.String(length=100), nullable=True),
    sa.Column('follow_up_msg', sa.Text(), nullable=True),
    sa.Column('follow_up_status', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_follow_up_queue_appointment_guid', 'app_mda_follow_up_queue', ['appointment_guid'], unique=False)
    op.create_index('idx_app_mda_follow_up_queue_created_date', 'app_mda_follow_up_queue', ['created_date'], unique=False)
    op.create_index('idx_app_mda_follow_up_queue_follow_up_status', 'app_mda_follow_up_queue', ['follow_up_status'], unique=False)
    op.create_index('idx_app_mda_follow_up_queue_patient_guid', 'app_mda_follow_up_queue', ['patient_guid'], unique=False)
    op.create_index('idx_app_mda_follow_up_queue_status', 'app_mda_follow_up_queue', ['status'], unique=False)
    op.create_index('idx_app_mda_follow_up_queue_updated_date', 'app_mda_follow_up_queue', ['updated_date'], unique=False)
    op.create_table('app_mda_patient',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('lead_guid', sa.UUID(), nullable=True),
    sa.Column('user_guid', sa.UUID(), nullable=True),
    sa.Column('clinic_hdr_guid', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_patient_clinic_hdr_guid', 'app_mda_patient', ['clinic_hdr_guid'], unique=False)
    op.create_index('idx_app_mda_patient_created_date', 'app_mda_patient', ['created_date'], unique=False)
    op.create_index('idx_app_mda_patient_email', 'app_mda_patient', ['email'], unique=False)
    op.create_index('idx_app_mda_patient_lead_guid', 'app_mda_patient', ['lead_guid'], unique=False)
    op.create_index('idx_app_mda_patient_name', 'app_mda_patient', ['name'], unique=False)
    op.create_index('idx_app_mda_patient_phone', 'app_mda_patient', ['phone'], unique=False)
    op.create_index('idx_app_mda_patient_status', 'app_mda_patient', ['status'], unique=False)
    op.create_index('idx_app_mda_patient_updated_date', 'app_mda_patient', ['updated_date'], unique=False)
    op.create_index('idx_app_mda_patient_user_guid', 'app_mda_patient', ['user_guid'], unique=False)
    op.create_table('app_mda_patient_lead',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('lead_status', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_patient_lead_created_date', 'app_mda_patient_lead', ['created_date'], unique=False)
    op.create_index('idx_app_mda_patient_lead_name', 'app_mda_patient_lead', ['name'], unique=False)
    op.create_index('idx_app_mda_patient_lead_phone', 'app_mda_patient_lead', ['phone'], unique=False)
    op.create_index('idx_app_mda_patient_lead_status', 'app_mda_patient_lead', ['status'], unique=False)
    op.create_index('idx_app_mda_patient_lead_status_of_lead', 'app_mda_patient_lead', ['lead_status'], unique=False)
    op.create_table('app_mda_prescription',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('appointment_guid', sa.UUID(), nullable=True),
    sa.Column('patient_guid', sa.UUID(), nullable=True),
    sa.Column('medicine_name', sa.String(length=255), nullable=True),
    sa.Column('dosage', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_prescription_appointment_guid', 'app_mda_prescription', ['appointment_guid'], unique=False)
    op.create_index('idx_app_mda_prescription_created_date', 'app_mda_prescription', ['created_date'], unique=False)
    op.create_index('idx_app_mda_prescription_dosage', 'app_mda_prescription', ['dosage'], unique=False)
    op.create_index('idx_app_mda_prescription_duration', 'app_mda_prescription', ['duration'], unique=False)
    op.create_index('idx_app_mda_prescription_frequency', 'app_mda_prescription', ['frequency'], unique=False)
    op.create_index('idx_app_mda_prescription_medicine_name', 'app_mda_prescription', ['medicine_name'], unique=False)
    op.create_index('idx_app_mda_prescription_patient_guid', 'app_mda_prescription', ['patient_guid'], unique=False)
    op.create_index('idx_app_mda_prescription_status', 'app_mda_prescription', ['status'], unique=False)
    op.create_index('idx_app_mda_prescription_updated_date', 'app_mda_prescription', ['updated_date'], unique=False)
    op.create_table('app_mda_prmn',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('user_guid', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_prmn_created_date', 'app_mda_prmn', ['created_date'], unique=False)
    op.create_index('idx_app_mda_prmn_role', 'app_mda_prmn', ['role'], unique=False)
    op.create_index('idx_app_mda_prmn_status', 'app_mda_prmn', ['status'], unique=False)
    op.create_index('idx_app_mda_prmn_user_guid', 'app_mda_prmn', ['user_guid'], unique=False)
    op.create_table('app_mda_user',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_user_created_date', 'app_mda_user', ['created_date'], unique=False)
    op.create_index('idx_app_mda_user_email', 'app_mda_user', ['email'], unique=False)
    op.create_index('idx_app_mda_user_phone', 'app_mda_user', ['phone'], unique=False)
    op.create_index('idx_app_mda_user_status', 'app_mda_user', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_app_mda_user_status', table_name='app_mda_user')
    op.drop_index('idx_app_mda_user_phone', table_name='app_mda_user')
    op.drop_index('idx_app_mda_user_email', table_name='app_mda_user')
    op.drop_index('idx_app_mda_user_created_date', table_name='app_mda_user')
    op.drop_table('app_mda_user')
    op.drop_index('idx_app_mda_prmn_user_guid', table_name='app_mda_prmn')
    op.drop_index('idx_app_mda_prmn_status', table_name='app_mda_prmn')
    op.drop_index('idx_app_mda_prmn_role', table_name='app_mda_prmn')
    op.drop_index('idx_app_mda_prmn_created_date', table_name='app_mda_prmn')
    op.drop_table('app_mda_prmn')
    op.drop_index('idx_app_mda_prescription_updated_date', table_name='app_mda_prescription')
    op.drop_index('idx_app_mda_prescription_status', table_name='app_mda_prescription')
    op.drop_index('idx_app_mda_prescription_patient_guid', table_name='app_mda_prescription')
    op.drop_index('idx_app_mda_prescription_medicine_name', table_name='app_mda_prescription')
    op.drop_index('idx_app_mda_prescription_frequency', table_name='app_mda_prescription')
    op.drop_index('idx_app_mda_prescription_duration', table_name='app_mda_prescription')
    op.drop_index('idx_app_mda_prescription_dosage', table_name='app_mda_prescription')
    op.drop_index('idx_app_mda_prescription_created_date', table_name='app_mda_prescription')
    op.drop_index('idx_app_mda_prescription_appointment_guid', table_name='app_mda_prescription')
    op.drop_table('app_mda_prescription')
    op.drop_index('idx_app_mda_patient_lead_status_of_lead', table_name='app_mda_patient_lead')
    op.drop_index('idx_app_mda_patient_lead_status', table_name='app_mda_patient_lead')
    op.drop_index('idx_app_mda_patient_lead_phone', table_name='app_mda_patient_lead')
    op.drop_index('idx_app_mda_patient_lead_name', table_name='app_mda_patient_lead')
    op.drop_index('idx_app_mda_patient_lead_created_date', table_name='app_mda_patient_lead')
    op.drop_table('app_mda_patient_lead')
    op.drop_index('idx_app_mda_patient_user_guid', table_name='app_mda_patient')
    op.drop_index('idx_app_mda_patient_updated_date', table_name='app_mda_patient')
    op.drop_index('idx_app_mda_patient_status', table_name='app_mda_patient')
    op.drop_index('idx_app_mda_patient_phone', table_name='app_mda_patient')
    op.drop_index('idx_app_mda_patient_name', table_name='app_mda_patient')
    op.drop_index('idx_app_mda_patient_lead_guid', table_name='app_mda_patient')
    op.drop_index('idx_app_mda_patient_email', table_name='app_mda_patient')
    op.drop_index('idx_app_mda_patient_created_date', table_name='app_mda_patient')
    op.drop_index('idx_app_mda_patient_clinic_hdr_guid', table_name='app_mda_patient')
    op.drop_table('app_mda_patient')
    op.drop_index('idx_app_mda_follow_up_queue_updated_date', table_name='app_mda_follow_up_queue')
    op.drop_index('idx_app_mda_follow_up_queue_status', table_name='app_mda_follow_up_queue')
    op.drop_index('idx_app_mda_follow_up_queue_patient_guid', table_name='app_mda_follow_up_queue')
    op.drop_index('idx_app_mda_follow_up_queue_follow_up_status', table_name='app_mda_follow_up_queue')
    op.drop_index('idx_app_mda_follow_up_queue_created_date', table_name='app_mda_follow_up_queue')
    op.drop_index('idx_app_mda_follow_up_queue_appointment_guid', table_name='app_mda_follow_up_queue')
    op.drop_table('app_mda_follow_up_queue')
    op.drop_index('idx_app_mda_doctor_patient_link_updated_date', table_name='app_mda_doctor_patient_link')
    op.drop_index('idx_app_mda_doctor_patient_link_status', table_name='app_mda_doctor_patient_link')
    op.drop_index('idx_app_mda_doctor_patient_link_patient_guid', table_name='app_mda_doctor_patient_link')
    op.drop_index('idx_app_mda_doctor_patient_link_doctor_guid', table_name='app_mda_doctor_patient_link')
    op.drop_index('idx_app_mda_doctor_patient_link_created_date', table_name='app_mda_doctor_patient_link')
    op.drop_table('app_mda_doctor_patient_link')
    op.drop_index('idx_app_mda_doctor_cred_status', table_name='app_mda_doctor_cred')
    op.drop_index('idx_app_mda_doctor_cred_doctor_guid', table_name='app_mda_doctor_cred')
    op.drop_index('idx_app_mda_doctor_cred_created_date', table_name='app_mda_doctor_cred')
    op.drop_table('app_mda_doctor_cred')
    op.drop_index('idx_app_mda_doctor_availability_updated_date', table_name='app_mda_doctor_availability')
    op.drop_index('idx_app_mda_doctor_availability_status', table_name='app_mda_doctor_availability')
    op.drop_index('idx_app_mda_doctor_availability_start_time', table_name='app_mda_doctor_availability')
    op.drop_index('idx_app_mda_doctor_availability_slot_duration_minutes', table_name='app_mda_doctor_availability')
    op.drop_index('idx_app_mda_doctor_availability_end_time', table_name='app_mda_doctor_availability')
    op.drop_index('idx_app_mda_doctor_availability_doctor_guid', table_name='app_mda_doctor_availability')
    op.drop_index('idx_app_mda_doctor_availability_day_of_week', table_name='app_mda_doctor_availability')
    op.drop_index('idx_app_mda_doctor_availability_created_date', table_name='app_mda_doctor_availability')
    op.drop_table('app_mda_doctor_availability')
    op.drop_index('idx_app_mda_doctor_user_guid', table_name='app_mda_doctor')
    op.drop_index('idx_app_mda_doctor_status', table_name='app_mda_doctor')
    op.drop_index('idx_app_mda_doctor_specialty', table_name='app_mda_doctor')
    op.drop_index('idx_app_mda_doctor_phone', table_name='app_mda_doctor')
    op.drop_index('idx_app_mda_doctor_name', table_name='app_mda_doctor')
    op.drop_index('idx_app_mda_doctor_email', table_name='app_mda_doctor')
    op.drop_index('idx_app_mda_doctor_created_date', table_name='app_mda_doctor')
    op.drop_index('idx_app_mda_doctor_clinic_hdr_guid', table_name='app_mda_doctor')
    op.drop_table('app_mda_doctor')
    op.drop_index('idx_app_mda_clinic_hdr_updated_date', table_name='app_mda_clinic_hdr')
    op.drop_index('idx_app_mda_clinic_hdr_status', table_name='app_mda_clinic_hdr')
    op.drop_index('idx_app_mda_clinic_hdr_name', table_name='app_mda_clinic_hdr')
    op.drop_index('idx_app_mda_clinic_hdr_created_date', table_name='app_mda_clinic_hdr')
    op.drop_table('app_mda_clinic_hdr')
    op.drop_index('idx_app_mda_appointment_session_updated_date', table_name='app_mda_appointment_session')
    op.drop_index('idx_app_mda_appointment_session_status', table_name='app_mda_appointment_session')
    op.drop_index('idx_app_mda_appointment_session_reviewed_by_doctor', table_name='app_mda_appointment_session')
    op.drop_index('idx_app_mda_appointment_session_doctor_guid', table_name='app_mda_appointment_session')
    op.drop_index('idx_app_mda_appointment_session_created_date', table_name='app_mda_appointment_session')
    op.drop_index('idx_app_mda_appointment_session_appointment_guid', table_name='app_mda_appointment_session')
    op.drop_table('app_mda_appointment_session')
    op.drop_index('idx_app_mda_appointment_updated_date', table_name='app_mda_appointment')
    op.drop_index('idx_app_mda_appointment_status_of_appt', table_name='app_mda_appointment')
    op.drop_index('idx_app_mda_appointment_status', table_name='app_mda_appointment')
    op.drop_index('idx_app_mda_appointment_scheduled_start', table_name='app_mda_appointment')
    op.drop_index('idx_app_mda_appointment_scheduled_end', table_name='app_mda_appointment')
    op.drop_index('idx_app_mda_appointment_patient_guid', table_name='app_mda_appointment')
    op.drop_index('idx_app_mda_appointment_doctor_guid', table_name='app_mda_appointment')
    op.drop_index('idx_app_mda_appointment_created_date', table_name='app_mda_appointment')
    op.drop_index('idx_app_mda_appointment_clinic_guid', table_name='app_mda_appointment')
    op.drop_table('app_mda_appointment')
    # ### end Alembic commands ###
