"""add app_mda_appointment_note table

Revision ID: d8e28cfe4fa2
Revises: 6ae79be1298d
Create Date: 2026-06-18 07:35:14.621838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e28cfe4fa2'
down_revision: Union[str, Sequence[str], None] = '6ae79be1298d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_mda_appointment_note',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('main_complaint', sa.Text(), nullable=True),
    sa.Column('blood_pressure', sa.String(length=11), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('oxygen_saturation', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_app_mda_appointment_note_created_date', 'app_mda_appointment_note', ['created_date'], unique=False)
    op.create_index('idx_app_mda_appointment_note_status', 'app_mda_appointment_note', ['status'], unique=False)
    op.create_index('idx_app_mda_appointment_note_updated_date', 'app_mda_appointment_note', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_app_mda_appointment_note_updated_date', table_name='app_mda_appointment_note')
    op.drop_index('idx_app_mda_appointment_note_status', table_name='app_mda_appointment_note')
    op.drop_index('idx_app_mda_appointment_note_created_date', table_name='app_mda_appointment_note')
    op.drop_table('app_mda_appointment_note')
    # ### end Alembic commands ###
